### ASSIGNMENT - 6

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

In [4]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
dataset.shape

(150, 5)

In [7]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [9]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [10]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 1.07399735,  0.05176719,  1.06692515,  1.5595129 ],
       [-1.25367751,  0.05176719, -1.20413503, -1.27791925],
       [-0.8861499 ,  1.66230189, -1.20413503, -1.27791925],
       [-1.74371432, -0.1783092 , -1.37446455, -1.27791925],
       [-0.39611309,  0.97207273, -1.37446455, -1.27791925],
       [ 1.80905256, -0.40838559,  1.46436068,  0.78566777],
       [-1.37618671,  0.28184357, -1.20413503, -1.27791925],
       [-0.02858548, -0.86853836,  0.10172457,  0.01182263],
       [-0.02858548, -0.86853836,  0.78304263,  0.91464196],
       [-0.8861499 ,  1.4322255 , -1.26091154, -1.01997088],
       [ 0.58396053,  0.51191996,  1.29403117,  1.68848709],
       [-0.7636407 ,  0.97207273, -1.26091154, -1.27791925],
       [ 0.58396053,  0.51191996,  0.55593661,  0.52771939],
       [ 1.07399735,  0.51191996,  1.12370165,  1.68848709],
       [ 0.46145133,  0.74199635,  0.95337214,  1.43053871],
       [ 0.33894213, -0.40838559,  0.55593661,  0.26977101],
       [ 1.07399735,  0.

In [11]:
X_test

array([[ 2.29908938, -0.1783092 ,  1.35080767,  1.43053871],
       [-0.7636407 , -0.86853836,  0.10172457,  0.26977101],
       [-1.13116831, -0.1783092 , -1.31768804, -1.27791925],
       [ 2.29908938, -0.63846197,  1.6914667 ,  1.04361614],
       [-0.51862229,  1.89237828, -1.14735853, -1.01997088],
       [ 1.31901575,  0.05176719,  0.66948962,  0.3987452 ],
       [ 0.58396053, -0.86853836,  0.66948962,  0.78566777],
       [-0.27360389, -1.32869113,  0.10172457, -0.11715155],
       [ 0.58396053, -1.32869113,  0.72626612,  0.91464196],
       [-0.39611309, -1.55876752,  0.04494807, -0.11715155],
       [ 0.82897894, -0.1783092 ,  1.01014864,  0.78566777],
       [-0.8861499 ,  1.66230189, -1.03380552, -1.01997088],
       [ 0.21643293, -0.40838559,  0.4423836 ,  0.3987452 ],
       [ 0.70646974,  0.05176719,  1.01014864,  0.78566777],
       [ 0.82897894, -0.1783092 ,  0.83981913,  1.04361614],
       [ 0.33894213, -0.1783092 ,  0.4991601 ,  0.26977101],
       [ 2.17658017, -0.

In [12]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [13]:
y_pred = classifier.predict(X_test) 
y_pred


array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica', 'setosa', 'versicolor', 'virginica', 'virginica',
       'versicolor', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'versicolor', 'virginica', 'setosa', 'versicolor'],
      dtype='<U10')

In [14]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 9,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 10]], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9666666666666667


In [16]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0    virginica        virginica
1   versicolor       versicolor
2       setosa           setosa
3    virginica        virginica
4       setosa           setosa
5   versicolor        virginica
6    virginica        virginica
7   versicolor       versicolor
8    virginica        virginica
9   versicolor       versicolor
10   virginica        virginica
11      setosa           setosa
12  versicolor       versicolor
13   virginica        virginica
14   virginica        virginica
15  versicolor       versicolor
16   virginica        virginica
17      setosa           setosa
18      setosa           setosa
19  versicolor       versicolor
20  versicolor       versicolor
21  versicolor       versicolor
22      setosa           setosa
23      setosa           setosa
24      setosa           setosa
25   virginica        virginica
26  versicolor       versicolor
27   virginica        virginica
28      setosa           setosa
29  versicolor       versicolor